server:
  port: 8095

spring:
  application:
    name: microservice-transaccion
 datasource:  
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/transaccion?useSSL=false&serverTimezone=UTC
  username: root
  password: 12345678
jpa:
  hibernate:
    ddl-auto: create
  database: mysql
  database-platform: org.hibernate.dialect.MySQLDialect
config:
  import: optional:configserver:http://localhost:8888
  
eureka:
  hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/