server:
  port: 9000

spring:
  application:
    name: ibkr-adapter

# Configuración del cliente Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

# Configuración específica para la API de Interactive Brokers
ibkr:
  api:
    host: 127.0.0.1
    port: 7497      # Puerto para Paper Trading en TWS
    clientId: 101